
export const FETCH_RATES_FROM_API_LOADING = 'FETCH_RATES_FROM_API_LOADING';
export const FETCH_RATES_FROM_API_ERROR = 'FETCH_RATES_FROM_API_ERROR';
export const FETCH_RATES_FROM_API_SUCCESS = 'FETCH_RATES_FROM_API_SUCCESS';

export const SET_USD = 'SET_USD';
export const SET_BTC = 'SET_BTC';

export const SET_AMOUNT = 'SET_AMOUNT';